# Support Doctors Without Borders / MSF through our AI Village fundraiser
custom:
  - https://www.every.org/doctors-without-borders/f/ai-village-turns-1-support
  - https://events.doctorswithoutborders.org/campaigns/ai-village-2026
